# -*- mode: toml -*-
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
"$schema" = "https://pixi.sh/v0.59.0/schema/manifest/schema.json"

[workspace]
name = "ocaml-feedstock"
version = "3.54.2"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/ocaml-feedstock"
authors = ["@conda-forge/ocaml"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "linux-ppc64le", "osx-64", "osx-arm64", "win-64"]
requires-pixi = ">=0.59.0"

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in rattler-build build directory."
[tasks.build]
cmd = "rattler-build build --recipe recipe"
description = "Build ocaml-feedstock directly (without setup scripts), no particular variant specified"
[tasks."build-linux_64_TG_linux-64"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_TG_linux-64.yaml"
description = "Build ocaml-feedstock with variant linux_64_TG_linux-64 directly (without setup scripts)"
[tasks."inspect-linux_64_TG_linux-64"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_TG_linux-64.yaml"
description = "List contents of ocaml-feedstock packages built for variant linux_64_TG_linux-64"
[tasks."build-linux_64_TG_linux-aarch64"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_TG_linux-aarch64.yaml"
description = "Build ocaml-feedstock with variant linux_64_TG_linux-aarch64 directly (without setup scripts)"
[tasks."inspect-linux_64_TG_linux-aarch64"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_TG_linux-aarch64.yaml"
description = "List contents of ocaml-feedstock packages built for variant linux_64_TG_linux-aarch64"
[tasks."build-linux_64_TG_linux-ppc64le"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_TG_linux-ppc64le.yaml"
description = "Build ocaml-feedstock with variant linux_64_TG_linux-ppc64le directly (without setup scripts)"
[tasks."inspect-linux_64_TG_linux-ppc64le"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_TG_linux-ppc64le.yaml"
description = "List contents of ocaml-feedstock packages built for variant linux_64_TG_linux-ppc64le"
[tasks."build-linux_aarch64_TG_linux-aarch64"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_TG_linux-aarch64.yaml"
description = "Build ocaml-feedstock with variant linux_aarch64_TG_linux-aarch64 directly (without setup scripts)"
[tasks."inspect-linux_aarch64_TG_linux-aarch64"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_TG_linux-aarch64.yaml"
description = "List contents of ocaml-feedstock packages built for variant linux_aarch64_TG_linux-aarch64"
[tasks."build-linux_ppc64le_TG_linux-ppc64le"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_ppc64le_TG_linux-ppc64le.yaml"
description = "Build ocaml-feedstock with variant linux_ppc64le_TG_linux-ppc64le directly (without setup scripts)"
[tasks."inspect-linux_ppc64le_TG_linux-ppc64le"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_ppc64le_TG_linux-ppc64le.yaml"
description = "List contents of ocaml-feedstock packages built for variant linux_ppc64le_TG_linux-ppc64le"
[tasks."build-osx_64_TG_osx-64"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_TG_osx-64.yaml"
description = "Build ocaml-feedstock with variant osx_64_TG_osx-64 directly (without setup scripts)"
[tasks."inspect-osx_64_TG_osx-64"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_TG_osx-64.yaml"
description = "List contents of ocaml-feedstock packages built for variant osx_64_TG_osx-64"
[tasks."build-osx_64_TG_osx-arm64"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_TG_osx-arm64.yaml"
description = "Build ocaml-feedstock with variant osx_64_TG_osx-arm64 directly (without setup scripts)"
[tasks."inspect-osx_64_TG_osx-arm64"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_TG_osx-arm64.yaml"
description = "List contents of ocaml-feedstock packages built for variant osx_64_TG_osx-arm64"
[tasks."build-osx_arm64_TG_osx-arm64"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_TG_osx-arm64.yaml"
description = "Build ocaml-feedstock with variant osx_arm64_TG_osx-arm64 directly (without setup scripts)"
[tasks."inspect-osx_arm64_TG_osx-arm64"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_TG_osx-arm64.yaml"
description = "List contents of ocaml-feedstock packages built for variant osx_arm64_TG_osx-arm64"
[tasks."build-win_64_TG_win-64_CC_mingw"]
cmd = "rattler-build build --recipe recipe -m .ci_support/win_64_TG_win-64_CC_mingw.yaml"
description = "Build ocaml-feedstock with variant win_64_TG_win-64_CC_mingw directly (without setup scripts)"
[tasks."inspect-win_64_TG_win-64_CC_mingw"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_TG_win-64_CC_mingw.yaml"
description = "List contents of ocaml-feedstock packages built for variant win_64_TG_win-64_CC_mingw"
[tasks."build-win_64_TG_win-64_CC_vs"]
cmd = "rattler-build build --recipe recipe -m .ci_support/win_64_TG_win-64_CC_vs.yaml"
description = "Build ocaml-feedstock with variant win_64_TG_win-64_CC_vs directly (without setup scripts)"
[tasks."inspect-win_64_TG_win-64_CC_vs"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_TG_win-64_CC_vs.yaml"
description = "List contents of ocaml-feedstock packages built for variant win_64_TG_win-64_CC_vs"

[feature.smithy.dependencies]
conda-smithy = "*"
[feature.smithy.tasks.build-locally]
cmd = "python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[feature.smithy.tasks.smithy]
cmd = "conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[feature.smithy.tasks.rerender]
cmd = "conda-smithy rerender"
description = "Rerender the feedstock."
[feature.smithy.tasks.lint]
cmd = "conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[environments]
smithy = ["smithy"]

# This is a copy of default, to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = []
